spring:
  profiles:
    active: development

---

spring:
  profiles: development
  application:
    name: course-registry
  datasource:
    url: jdbc:postgresql://localhost:5433/registerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create, update

server:
  port: 8180

logging:
  level:
    com:
      ucuenca: DEBUG

---

spring:
  profiles: docker
  application:
    name: course-registry

server:
  port: 8080

logging:
  level:
    com:
      ucuenca: INFO