spring:
  profiles:
    active: development

---

spring:
  profiles: development
  application:
    name: course-registry

server:
  port: 8180

logging:
  level:
    com:
      ucuenca: DEBUG

---

spring:
  profiles: docker
  application:
    name: course-registry

server:
  port: 8080

logging:
  level:
    com:
      ucuenca: INFO