INSERT INTO tbl_courses VALUES ('SUB001', 'MATEMATICAS');
INSERT INTO tbl_courses VALUES ('SUB002', 'CALCULO');
INSERT INTO tbl_courses VALUES ('SUB003', 'ALGEBRA');
INSERT INTO tbl_courses VALUES ('SUB004', 'PROGRAMACION');
INSERT INTO tbl_courses VALUES ('SUB005', 'ESTADISTICA');
INSERT INTO tbl_faculty VALUES ('FAC001', 'INGENIERIA');
INSERT INTO tbl_faculty VALUES ('FAC002', 'FILOSOFIA');
INSERT INTO tbl_faculty VALUES ('FAC003', 'ECONOMIA');
INSERT INTO tbl_faculty VALUES ('FAC004', 'MEDICINA');

