version: '3'
services:
  course-registry:
    image: ucuenca/course-registry:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8082:8080
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: registerdb
      SPRING_PROFILES_ACTIVE: docker