spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: registration-web
server:
  port: 5000
logging:
  level:
    org:
      springframework:
        security: DEBUG
---
spring:
  profiles: docker
  application:
    name: registration-web
server:
  port: 5000
logging:
  level:
    org:
      springframework:
        security: DEBUG