version: '3'
services:
  enrollment:
    image: ucuenca/enrollment:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8280:8080
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: enrollmentdb
      SPRING_PROFILES_ACTIVE: docker